{
 "title": "Styx System Overview",
 "tags": [
  "Styx",
  "General"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU per phase (ms)",
   "type": "timeseries",
   "description": "The amount of CPU time consumed by each of the different transactional phases in ms",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(phase_cpu_ms_total[5s])",
     "legendFormat": "{{phase}} ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Ingress per phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(phase_net_rx_bytes_total[5s])",
     "legendFormat": "{{phase}} ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Egress per phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(phase_net_tx_bytes_total[5s])",
     "legendFormat": "{{phase}} ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "description": "System-wide CPU utilization",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (worker_cpu_usage_percent > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (worker_memory_usage_mb) * 1000000"
    }
   ]
  },
  {
   "title": "Ingress Network (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(worker_network_rx_kb[5s])) * 1000"
    }
   ]
  },
  {
   "title": "Egress Network (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(worker_network_tx_kb[5s])) * 1000"
    }
   ]
  },
  {
   "title": "Input Rate",
   "type": "timeseries",
   "description": "Rate of incoming load across the entire system ",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(input_rate_counter_total[15s]))",
     "legendFormat": "Total Input Rate"
    }
   ]
  },
  {
   "title": "TPS (committed)",
   "type": "timeseries",
   "description": "Throughput per epoch of the committed transactions",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(epoch_total_transactions_total[15s]))"
    }
   ]
  },
  {
   "title": "Backlog (Lag)",
   "type": "timeseries",
   "description": "Backlog - number of input elements that have been consumed by styx but not yet processed (lag)",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "targets": [
    { "expr": "sum(queue_backlog)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Commit & Abort Count",
   "type": "timeseries",
   "description": "Calculates the per-second average rate of the different types of commits and aborts for each epoch",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "rate(epoch_committed_lock_free_total[15s]) > 0",
     "legendFormat": "lock_free_commited ({{exported_instance}})"
    },
    {
     "expr": "rate(epoch_committed_fallback_total[15s])> 0",
     "legendFormat": "fallback_comitted ({{exported_instance}})"
    },
    {
     "expr": "rate(epoch_logic_aborts_total[15s]) > 0",
     "legendFormat": "logic_aborts ({{exported_instance}})"
    },
    {
     "expr": "rate(epoch_concurrency_aborts_total[15s]) > 0",
     "legendFormat": "concurrency_aborts ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Average Latency Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(latency_breakdown > 0) by (component)",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Worker Utilisation",
   "type": "timeseries",
   "description": "CPU Ratio - ratio of processing time to total epoch time. Calculated as latency needed for processing heavy phases divided by the total epoch time\nIO Ratio - similar but for IO",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(worker_cpu_utilization[5s]) * 100",
     "legendFormat": "CPU ({{exported_instance}})"
    },
    {
     "expr": "avg_over_time(worker_io_utilization[5s]) * 100",
     "legendFormat": "IO ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Transaction Latency",
   "type": "timeseries",
   "description": "Total latency of commited transactions",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(worker_epoch_latency_ms)" }
   ]
  },
  {
   "title": "Operator Execution time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (operator) (operator_latency_ms)",
     "legendFormat": "{{operator}}"
    }
   ]
  },
  {
   "title": "Operator TPS",
   "type": "timeseries",
   "description": "TPS per operator -> calculated as operator execution time in the epoch / total epoch latency",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "avg by (operator) (rate(operator_tps_total[5s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Operator Call Count ",
   "type": "timeseries",
   "description": "Number of times a call goes through an operator during the epoch per worker",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "(rate(operator_call_count_total[15s])) > 0",
     "legendFormat": "{{operator}} ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Snapshot Latency",
   "type": "timeseries",
   "description": "Total latency for taking a snapshot",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(worker_total_snapshotting_time_ms)"
    }
   ]
  },
  {
   "title": "Abort Rate (%)",
   "type": "timeseries",
   "description": "Percentage of aborted transactions",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(worker_abort_percent)" }
   ]
  },
  {
   "title": "Empty Epochs",
   "type": "status-history",
   "description": "1 if the epoch had no work (the input sequence is empty, the epoch was just syncing), 0 otherwise",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "avg_over_time(worker_empty_epoch[1s])",
     "legendFormat": "Worker: {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Idle time (ms)",
   "type": "timeseries",
   "description": "Time the worker spent idle in each epoch",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "idle_time_ms_per_second > 0",
     "legendFormat": "Idle time ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Time since last heartbeat (ms)",
   "type": "bargauge",
   "description": "Time since the last heartbeat for each worker",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time_since_last_heartbeat", "legendFormat": "{{exported_instance}}" }
   ]
  }
 ]
}